ALTER TABLE teams
ADD COLUMN IF NOT EXISTS league VARCHAR(50) DEFAULT 'EPL';

ALTER TABLE matches
ADD COLUMN IF NOT EXISTS league VARCHAR(50) DEFAULT 'EPL';

ALTER TABLE match_stats ADD COLUMN IF NOT EXISTS home_ppda FLOAT;

ALTER TABLE match_stats ADD COLUMN IF NOT EXISTS away_ppda FLOAT;

ALTER TABLE match_stats ADD COLUMN IF NOT EXISTS home_deep INT;

ALTER TABLE match_stats ADD COLUMN IF NOT EXISTS away_deep INT;